"""OreSat0 object dictionary and beacon constants."""

import os

from ..base import (
    BAT_CONFIG_PATH,
    C3_CONFIG_PATH,
    DXWIFI_CONFIG_PATH,
    FW_COMMON_CONFIG_PATH,
    GPS_CONFIG_PATH,
    IMU_CONFIG_PATH,
    SOLAR_CONFIG_PATH,
    ST_CONFIG_PATH,
    SW_COMMON_CONFIG_PATH,
)
from ..constants import NodeId

_CONFIGS_DIR = os.path.dirname(os.path.abspath(__file__))

BAT_OVERLAY_CONFIG_PATH = f"{_CONFIGS_DIR}/battery_overlay.yaml"

ORESAT0_BEACON_CONFIG_PATH = f"{_CONFIGS_DIR}/beacon.yaml"

ORESAT0_CARD_CONFIGS_PATH = {
    NodeId.C3: (C3_CONFIG_PATH, SW_COMMON_CONFIG_PATH),
    NodeId.BATTERY_1: (BAT_CONFIG_PATH, FW_COMMON_CONFIG_PATH, BAT_OVERLAY_CONFIG_PATH),
    NodeId.SOLAR_MODULE_1: (SOLAR_CONFIG_PATH, FW_COMMON_CONFIG_PATH),
    NodeId.SOLAR_MODULE_2: (SOLAR_CONFIG_PATH, FW_COMMON_CONFIG_PATH),
    NodeId.SOLAR_MODULE_3: (SOLAR_CONFIG_PATH, FW_COMMON_CONFIG_PATH),
    NodeId.SOLAR_MODULE_4: (SOLAR_CONFIG_PATH, FW_COMMON_CONFIG_PATH),
    NodeId.IMU: (IMU_CONFIG_PATH, FW_COMMON_CONFIG_PATH),
    NodeId.GPS: (GPS_CONFIG_PATH, SW_COMMON_CONFIG_PATH),
    NodeId.STAR_TRACKER_1: (ST_CONFIG_PATH, SW_COMMON_CONFIG_PATH),
    NodeId.DXWIFI: (DXWIFI_CONFIG_PATH, SW_COMMON_CONFIG_PATH),
}
