"""OreSat0.5 object dictionary and beacon constants."""

import os

import yaml

from .._yaml_to_od import (
    gen_fw_base_od,
    gen_od_db,
    get_c3_beacon_defs,
    get_c3_fram_defs,
    read_yaml_od_config,
)
from ..base import (
    BAT_CONFIG,
    C3_CONFIG,
    CFC_CONFIG,
    DXWIFI_CONFIG,
    FW_COMMON_CONFIG,
    GPS_CONFIG,
    IMU_CONFIG,
    RW_CONFIG,
    SOLAR_CONFIG,
    ST_CONFIG,
    SW_COMMON_CONFIG,
)
from ..constants import NodeId, OreSatId

_CONFIGS_DIR = os.path.dirname(os.path.abspath(__file__))

with open(f"{_CONFIGS_DIR}/beacon.yaml", "r") as f:
    ORESAT0_5_BEACON_CONFIG = yaml.safe_load(f)


ORESAT0_5_OD_DB = gen_od_db(
    OreSatId.ORESAT0_5,
    ORESAT0_5_BEACON_CONFIG,
    {
        NodeId.C3: (C3_CONFIG, SW_COMMON_CONFIG),
        NodeId.BATTERY_1: (BAT_CONFIG, FW_COMMON_CONFIG),
        NodeId.SOLAR_MODULE_1: (SOLAR_CONFIG, FW_COMMON_CONFIG),
        NodeId.SOLAR_MODULE_2: (SOLAR_CONFIG, FW_COMMON_CONFIG),
        NodeId.SOLAR_MODULE_3: (SOLAR_CONFIG, FW_COMMON_CONFIG),
        NodeId.SOLAR_MODULE_4: (SOLAR_CONFIG, FW_COMMON_CONFIG),
        NodeId.SOLAR_MODULE_5: (SOLAR_CONFIG, FW_COMMON_CONFIG),
        NodeId.SOLAR_MODULE_6: (SOLAR_CONFIG, FW_COMMON_CONFIG),
        NodeId.IMU: (IMU_CONFIG, FW_COMMON_CONFIG),
        NodeId.REACTION_WHEEL_1: (RW_CONFIG, FW_COMMON_CONFIG),
        NodeId.REACTION_WHEEL_2: (RW_CONFIG, FW_COMMON_CONFIG),
        NodeId.REACTION_WHEEL_3: (RW_CONFIG, FW_COMMON_CONFIG),
        NodeId.REACTION_WHEEL_4: (RW_CONFIG, FW_COMMON_CONFIG),
        NodeId.GPS: (GPS_CONFIG, SW_COMMON_CONFIG),
        NodeId.STAR_TRACKER_1: (ST_CONFIG, SW_COMMON_CONFIG),
        NodeId.DXWIFI: (DXWIFI_CONFIG, SW_COMMON_CONFIG),
        NodeId.CFC: (CFC_CONFIG, SW_COMMON_CONFIG),
    },
)

# direct access to ODs
ORESAT0_5_C3_OD = ORESAT0_5_OD_DB[NodeId.C3]
ORESAT0_5_BATTERY_1_OD = ORESAT0_5_OD_DB[NodeId.BATTERY_1]
ORESAT0_5_SOLAR_MODULE_1_OD = ORESAT0_5_OD_DB[NodeId.SOLAR_MODULE_1]
ORESAT0_5_SOLAR_MODULE_2_OD = ORESAT0_5_OD_DB[NodeId.SOLAR_MODULE_2]
ORESAT0_5_SOLAR_MODULE_3_OD = ORESAT0_5_OD_DB[NodeId.SOLAR_MODULE_3]
ORESAT0_5_SOLAR_MODULE_4_OD = ORESAT0_5_OD_DB[NodeId.SOLAR_MODULE_4]
ORESAT0_5_SOLAR_MODULE_5_OD = ORESAT0_5_OD_DB[NodeId.SOLAR_MODULE_5]
ORESAT0_5_SOLAR_MODULE_6_OD = ORESAT0_5_OD_DB[NodeId.SOLAR_MODULE_6]
ORESAT0_5_IMU_OD = ORESAT0_5_OD_DB[NodeId.IMU]
ORESAT0_5_REACTION_WHEEL_1_OD = ORESAT0_5_OD_DB[NodeId.REACTION_WHEEL_1]
ORESAT0_5_REACTION_WHEEL_2_OD = ORESAT0_5_OD_DB[NodeId.REACTION_WHEEL_2]
ORESAT0_5_REACTION_WHEEL_3_OD = ORESAT0_5_OD_DB[NodeId.REACTION_WHEEL_3]
ORESAT0_5_REACTION_WHEEL_4_OD = ORESAT0_5_OD_DB[NodeId.REACTION_WHEEL_4]
ORESAT0_5_GPS_OD = ORESAT0_5_OD_DB[NodeId.GPS]
ORESAT0_5_STAR_TRACKER_1_OD = ORESAT0_5_OD_DB[NodeId.STAR_TRACKER_1]
ORESAT0_5_DXWIFI_OD = ORESAT0_5_OD_DB[NodeId.DXWIFI]
ORESAT0_5_CFC_OD = ORESAT0_5_OD_DB[NodeId.CFC]

ORESAT0_5_BEACON_DEF = get_c3_beacon_defs(ORESAT0_5_C3_OD, ORESAT0_5_BEACON_CONFIG)
ORESAT0_5_FRAM_DEF = get_c3_fram_defs(ORESAT0_5_C3_OD, C3_CONFIG)

ORESAT0_5_FW_BASE_OD = gen_fw_base_od(OreSatId.ORESAT0_5, FW_COMMON_CONFIG)
